import { defineConfig } from 'tsup'

const NODE_BUILTINS = [
  'fs',
  'node:fs',
  'net',
  'node:net',
  'crypto',
  'node:crypto',
  'child_process',
  'node:child_process',
  'os',
  'node:os',
  'path',
  'node:path',
  'http',
  'node:http',
  'https',
  'node:https',
  'stream',
  'node:stream',
  'util',
  'node:util',
  'zlib',
  'node:zlib',
  'tls',
  'node:tls',
  'dns',
  'node:dns',
  'dgram',
  'node:dgram',
  'cluster',
  'node:cluster',
  'readline',
  'node:readline',
  'worker_threads',
  'node:worker_threads',
  'module',
  'node:module',
  'perf_hooks',
  'node:perf_hooks',
  'vm',
  'node:vm',
]

export default defineConfig({
  entry: { index: 'src/server/edge/index.ts' },
  outDir: 'dist/edge',
  format: ['esm'],
  dts: true,
  sourcemap: true,
  target: 'es2022',
  clean: true,
  splitting: false,
  minify: true,
  treeshake: true,
  external: ['tsx', ...NODE_BUILTINS],
})
