import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'server/index': 'src/server/index.ts',
    'server/http/index': 'src/server/http/index.ts',
    'server/router/index': 'src/server/router/index.ts',
    'server/middleware/index': 'src/server/middleware/index.ts',
    'server/controller/index': 'src/server/controller/index.ts',
    'server/container/index': 'src/server/container/index.ts',
    'server/auth/index': 'src/server/auth/index.ts',
    'server/gate/index': 'src/server/gate/index.ts',
    'server/cache/index': 'src/server/cache/index.ts',
    'server/storage/index': 'src/server/storage/index.ts',
    'server/events/index': 'src/server/events/index.ts',
    'server/database/index': 'src/server/database/index.ts',
    'server/audit/index': 'src/server/audit/index.ts',
    'server/webhook/index': 'src/server/webhook/index.ts',
    'server/search/index': 'src/server/search/index.ts',
    'server/ai/index': 'src/server/ai/index.ts',
    'server/graphql/index': 'src/server/graphql/index.ts',
    'server/admin/index': 'src/server/admin/index.ts',
    'server/flags/index': 'src/server/flags/index.ts',
    'server/schedule/index': 'src/server/schedule/index.ts',
    'server/profiler/index': 'src/server/profiler/index.ts',
    'server/observability/index': 'src/server/observability/index.ts',
    'server/i18n/index': 'src/server/i18n/index.ts',
    'server/billing/index': 'src/server/billing/index.ts',
    'server/isr/index': 'src/server/isr/index.ts',
    'server/edge/index': 'src/server/edge/index.ts',
    'server/health/index': 'src/server/health/index.ts',
    'server/notifications/index': 'src/server/notifications/index.ts',
    'server/view/index': 'src/server/view/index.ts',
    'server/debug/index': 'src/server/debug/index.ts',
    'server/env/index': 'src/server/env/index.ts',
    'server/rbac/index': 'src/server/rbac/index.ts',
    'server/tasks/index': 'src/server/tasks/index.ts',
    'server/queue/index': 'src/server/queue/index.ts',
    'server/mail/index': 'src/server/mail/index.ts',
    'server/websocket/index': 'src/server/websocket/index.ts',
    'server/testing/index': 'src/server/testing/index.ts',
    'server/plugin/index': 'src/server/plugin/index.ts',
    'server/plugin/presets': 'src/server/plugin/presets.ts',
    'server/plugin/registry': 'src/server/plugin/registry.ts',
    'server/openapi/index': 'src/server/openapi/index.ts',
    'client/index': 'src/client/index.ts',
    'client/signals/index': 'src/client/signals/index.ts',
    'client/vdom/index': 'src/client/vdom/index.ts',
    'client/vdom/jsx-runtime': 'src/client/vdom/jsx-runtime.ts',
    'rpc/index': 'src/rpc/index.ts',
    'schema/index': 'src/schema/index.ts',
    'cli/index': 'src/cli/index.ts',
    'native/index': 'src/native/index.ts',
    'native/hashing': 'src/native/hashing.ts',
    'native/crypto': 'src/native/crypto.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  target: 'node20',
  clean: true,
  splitting: true,
  minify: true,
  treeshake: true,
  external: ['tsx', 'ws', 'better-sqlite3', 'sharp'],
})
