const PKG_DEPS = { speexjs: 'latest' }
const PKG_DEVDEPS = { '@types/node': '^26.0.1', tsx: '^4.19.0', typescript: '^5.7.0' }

function pkg(name, scripts, extra = {}) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      type: 'module',
      private: true,
      scripts,
      dependencies: PKG_DEPS,
      devDependencies: { ...PKG_DEVDEPS, ...extra.devDependencies },
      ...extra,
    },
    null,
    2,
  )
}

function tsconfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        declaration: true,
        sourceMap: true,
        esModuleInterop: true,
        isolatedModules: true,
        resolveJsonModule: true,
        outDir: './dist',
        rootDir: './src',
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['src/**/*.ts'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  )
}

export const apiTemplate = {
  dirs: ['src/config', 'src/controllers', 'src/middleware', 'src/validators', 'src/docs'],
  files: {
    'package.json': (name) =>
      pkg(name, {
        dev: 'speexjs serve',
        build: 'speexjs build',
        start: 'node dist/index.js',
        lint: 'tsc --noEmit',
      }),
    'tsconfig.json': tsconfig(),
    'src/index.ts': [
      "import { speexjs, cors, bodyParser, throttle } from 'speexjs/server'",
      "import { AuthController } from './controllers/auth.controller.js'",
      "import { UserController } from './controllers/user.controller.js'",
      "import { ItemController } from './controllers/item.controller.js'",
      "import { rateLimiter } from './middleware/rate-limiter.js'",
      '',
      'const app = speexjs()',
      '',
      'app.use(cors())',
      'app.use(bodyParser())',
      'app.use(rateLimiter(100, 60000))',
      '',
      'app.controller(AuthController)',
      'app.controller(UserController)',
      'app.controller(ItemController)',
      '',
      "app.get('/api', async ({ response }) => {",
      '  return response.json({',
      "    name: 'SpeexJS API',",
      "    version: '0.1.0',",
      "    docs: '/api/docs',",
      '    endpoints: {',
      "      auth: { register: 'POST /api/auth/register', login: 'POST /api/auth/login' },",
      "      users: { list: 'GET /api/users', get: 'GET /api/users/:id' },",
      "      items: { list: 'GET /api/items', create: 'POST /api/items', get: 'GET /api/items/:id', update: 'PUT /api/items/:id', delete: 'DELETE /api/items/:id' },",
      '    },',
      '  })',
      '})',
      '',
      "app.get('/api/docs', async ({ response }) => {",
      '  return response.json({',
      "    openapi: '3.0.3',",
      "    info: { title: 'SpeexJS API', version: '0.1.0', description: 'RESTful API built with SpeexJS' },",
      "    servers: [{ url: '/api', description: 'API server' }],",
      '  })',
      '})',
      '',
      'export { app }',
    ].join('\n'),
    'src/config/index.ts': [
      'export const Config = {',
      "  port: Number(process.env.PORT ?? '3000'),",
      "  env: process.env.NODE_ENV ?? 'development',",
      "  isDev: (process.env.NODE_ENV ?? 'development') !== 'production',",
      "  isProd: process.env.NODE_ENV === 'production',",
      "  appKey: process.env.APP_KEY ?? '',",
      "  jwtSecret: process.env.JWT_SECRET ?? 'change-me-in-production',",
      '}',
    ].join('\n'),
    'src/controllers/auth.controller.ts': [
      "import { Controller, get, post } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      "import { scryptSync, randomBytes, timingSafeEqual } from 'node:crypto'",
      '',
      'let users = []',
      'let nextId = 1',
      'const sessions = {}',
      '',
      'function hashPassword(password) {',
      "  const salt = randomBytes(16).toString('hex')",
      "  const hash = scryptSync(password, salt, 64).toString('hex')",
      '  return `${salt}:${hash}`',
      '}',
      '',
      'function verifyPassword(password, stored) {',
      "  const [salt, hash] = stored.split(':')",
      '  const derivedHash = scryptSync(password, salt, 64)',
      "  return timingSafeEqual(derivedHash, Buffer.from(hash, 'hex'))",
      '}',
      '',
      'const RegisterSchema = schema.object({',
      '  email: schema.string().email(),',
      '  password: schema.string().min(8).max(100),',
      '  name: schema.string().min(2).max(100),',
      '})',
      '',
      'const LoginSchema = schema.object({',
      '  email: schema.string().email(),',
      '  password: schema.string().min(1),',
      '})',
      '',
      'export class AuthController extends Controller {',
      "  @post('/api/auth/register')",
      '  async register({ request, response }) {',
      '    const body = await request.body()',
      '    const result = RegisterSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    if (users.find(u => u.email === result.data.email)) {',
      "      return response.status(409).json({ error: 'CONFLICT', message: 'Email already registered' })",
      '    }',
      '    const hashed = hashPassword(result.data.password)',
      '    const user = { id: nextId++, email: result.data.email, name: result.data.name, password: hashed, createdAt: new Date().toISOString() }',
      '    users.push(user)',
      '    const token = `tok_${user.id}_${Date.now()}`',
      '    sessions[token] = user.id',
      '    return response.status(201).json({ data: { id: user.id, email: user.email, name: user.name, token } })',
      '  }',
      '',
      "  @post('/api/auth/login')",
      '  async login({ request, response }) {',
      '    const body = await request.body()',
      '    const result = LoginSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const user = users.find(u => u.email === result.data.email)',
      "    if (!user) return response.status(401).json({ error: 'UNAUTHORIZED', message: 'Invalid credentials' })",
      '    const valid = verifyPassword(result.data.password, user.password)',
      "    if (!valid) return response.status(401).json({ error: 'UNAUTHORIZED', message: 'Invalid credentials' })",
      '    const token = `tok_${user.id}_${Date.now()}`',
      '    sessions[token] = user.id',
      '    return response.json({ data: { id: user.id, email: user.email, name: user.name, token } })',
      '  }',
      '',
      "  @get('/api/auth/me')",
      '  async me({ request, response }) {',
      "    const authHeader = request.headers.get('authorization')",
      "    if (!authHeader) return response.status(401).json({ error: 'UNAUTHORIZED', message: 'Missing token' })",
      "    const token = authHeader.replace('Bearer ', '')",
      '    const userId = sessions[token]',
      "    if (!userId) return response.status(401).json({ error: 'UNAUTHORIZED', message: 'Invalid token' })",
      '    const user = users.find(u => u.id === userId)',
      "    if (!user) return response.status(401).json({ error: 'UNAUTHORIZED', message: 'User not found' })",
      '    return response.json({ data: { id: user.id, email: user.email, name: user.name } })',
      '  }',
      '',
      "  @post('/api/auth/logout')",
      '  async logout({ request, response }) {',
      "    const authHeader = request.headers.get('authorization')",
      '    if (authHeader) {',
      "      const token = authHeader.replace('Bearer ', '')",
      '      delete sessions[token]',
      '    }',
      "    return response.json({ message: 'Logged out' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/user.controller.ts': [
      "import { Controller, get } from 'speexjs/server'",
      '',
      'let users = [',
      "  { id: 1, email: 'admin@api.local', name: 'Admin', createdAt: new Date().toISOString() },",
      ']',
      '',
      'export class UserController extends Controller {',
      "  @get('/api/users')",
      '  async index({ response, query }) {',
      '    const page = Number(query.page) || 1',
      '    const limit = Number(query.limit) || 20',
      '    const offset = (page - 1) * limit',
      '    const paginated = users.slice(offset, offset + limit)',
      '    return response.json({',
      '      data: paginated,',
      '      meta: { total: users.length, page, limit, totalPages: Math.ceil(users.length / limit) },',
      '    })',
      '  }',
      '',
      "  @get('/api/users/:id')",
      '  async show({ response, params }) {',
      '    const user = users.find(u => u.id === Number(params.id))',
      "    if (!user) return response.status(404).json({ error: 'NOT_FOUND', message: 'User not found' })",
      '    return response.json({ data: user })',
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/item.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Item { id: number; name: string; description: string; price: number; createdAt: string; updatedAt: string }',
      '',
      'let items = [',
      "  { id: 1, name: 'Sample Item', description: 'A sample API item', price: 9.99, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },",
      ']',
      'let nextId = 2',
      '',
      'const ItemSchema = schema.object({',
      '  name: schema.string().min(2).max(200),',
      '  description: schema.string().max(1000).optional(),',
      '  price: schema.number().min(0),',
      '})',
      '',
      'export class ItemController extends Controller {',
      "  @get('/api/items')",
      '  async index({ response, query }) {',
      '    const page = Number(query.page) || 1',
      '    const limit = Number(query.limit) || 20',
      '    const offset = (page - 1) * limit',
      '    const paginated = items.slice(offset, offset + limit)',
      '    return response.json({',
      '      data: paginated,',
      '      meta: { total: items.length, page, limit, totalPages: Math.ceil(items.length / limit) },',
      '    })',
      '  }',
      '',
      "  @get('/api/items/:id')",
      '  async show({ response, params }) {',
      '    const item = items.find(i => i.id === Number(params.id))',
      "    if (!item) return response.status(404).json({ error: 'NOT_FOUND', message: 'Item not found' })",
      '    return response.json({ data: item })',
      '  }',
      '',
      "  @post('/api/items')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = ItemSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const now = new Date().toISOString()',
      "    const item = { id: nextId++, ...result.data, description: result.data.description || '', createdAt: now, updatedAt: now }",
      '    items.push(item)',
      '    return response.status(201).json({ data: item })',
      '  }',
      '',
      "  @put('/api/items/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = items.findIndex(i => i.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Item not found' })",
      '    const body = await request.body()',
      '    const result = ItemSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    items[idx] = { ...items[idx], ...result.data, updatedAt: new Date().toISOString() }',
      '    return response.json({ data: items[idx] })',
      '  }',
      '',
      "  @del('/api/items/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = items.findIndex(i => i.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Item not found' })",
      '    items.splice(idx, 1)',
      "    return response.json({ message: 'Item deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/middleware/rate-limiter.ts': [
      "import type { RouteContext } from 'speexjs/server/router'",
      '',
      'const hits = new Map()',
      '',
      'export function rateLimiter(maxRequests = 100, windowMs = 60000) {',
      '  return (ctx, next) => {',
      "    const ip = ctx.request.headers.get('x-forwarded-for') || ctx.request.socket?.remoteAddress || 'unknown'",
      '    const key = String(ip)',
      '    const now = Date.now()',
      '    const entry = hits.get(key)',
      '    if (!entry || now > entry.resetAt) {',
      '      hits.set(key, { count: 1, resetAt: now + windowMs })',
      "      ctx.response.headers.set('X-RateLimit-Limit', String(maxRequests))",
      "      ctx.response.headers.set('X-RateLimit-Remaining', String(maxRequests - 1))",
      '      return next()',
      '    }',
      '    if (entry.count >= maxRequests) {',
      "      ctx.response.headers.set('Retry-After', String(Math.ceil((entry.resetAt - now) / 1000)))",
      "      ctx.response.status(429).json({ error: 'TOO_MANY_REQUESTS', message: 'Rate limit exceeded' })",
      '      return',
      '    }',
      '    entry.count++',
      "    ctx.response.headers.set('X-RateLimit-Limit', String(maxRequests))",
      "    ctx.response.headers.set('X-RateLimit-Remaining', String(maxRequests - entry.count))",
      '    return next()',
      '  }',
      '}',
    ].join('\n'),
    'src/middleware/auth.middleware.ts': [
      "import type { RouteContext } from 'speexjs/server/router'",
      '',
      'export function authenticate() {',
      '  return async (ctx, next) => {',
      "    const authHeader = ctx.request.headers.get('authorization')",
      "    if (!authHeader?.startsWith('Bearer ')) {",
      "      ctx.response.status(401).json({ error: 'UNAUTHORIZED', message: 'Missing or invalid authorization header' })",
      '      return',
      '    }',
      '    await next()',
      '  }',
      '}',
    ].join('\n'),
    '.env.example': ['PORT=3000', 'NODE_ENV=development', 'APP_KEY=', 'JWT_SECRET=change-me-in-production'].join('\n'),
    '.gitignore': ['node_modules/', 'dist/', '.env', '*.log'].join('\n'),
    'biome.json': JSON.stringify(
      {
        $schema: 'https://biomejs.dev/schemas/1.9.0/schema.json',
        organizeImports: { enabled: true },
        linter: { enabled: true, rules: { recommended: true } },
        formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineEnding: 'lf' },
      },
      null,
      2,
    ),
  },
}
