const PKG_DEPS = { speexjs: 'latest', marked: '^15.0.0' }
const PKG_DEVDEPS = { '@types/node': '^26.0.1', tsx: '^4.19.0', typescript: '^5.7.0' }

function pkg(name, scripts, extra = {}) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      type: 'module',
      private: true,
      scripts,
      dependencies: PKG_DEPS,
      devDependencies: { ...PKG_DEVDEPS, ...extra.devDependencies },
      ...extra,
    },
    null,
    2,
  )
}

function tsconfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        declaration: true,
        sourceMap: true,
        esModuleInterop: true,
        isolatedModules: true,
        resolveJsonModule: true,
        outDir: './dist',
        rootDir: './src',
        jsx: 'react-jsx',
        jsxImportSource: '@speexjs/vdom',
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  )
}

export const blogTemplate = {
  dirs: ['src/config', 'src/controllers', 'src/models', 'src/middleware', 'src/views', 'src/posts', 'public', 'resources/views/layouts'],
  files: {
    'package.json': (name) =>
      pkg(name, {
        dev: 'speexjs serve',
        build: 'speexjs build',
        start: 'node dist/index.js',
        lint: 'tsc --noEmit',
      }),
    'tsconfig.json': tsconfig(),
    'src/index.ts': [
      "import { speexjs, cors, bodyParser, staticFiles } from 'speexjs/server'",
      "import { PostController } from './controllers/post.controller.js'",
      "import { CategoryController } from './controllers/category.controller.js'",
      "import { CommentController } from './controllers/comment.controller.js'",
      "import { TagController } from './controllers/tag.controller.js'",
      '',
      'const app = speexjs()',
      '',
      'app.use(cors())',
      'app.use(bodyParser())',
      "app.use(staticFiles('public', { maxAge: 86400 }))",
      '',
      'app.controller(PostController)',
      'app.controller(CategoryController)',
      'app.controller(CommentController)',
      'app.controller(TagController)',
      '',
      "app.get('/', async ({ response }) => {",
      '  return response.html(`<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="UTF-8" />',
      '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
      '  <title>My Blog</title>',
      '  <link rel="stylesheet" href="/style.css" />',
      '</head>',
      '<body>',
      '  <nav>',
      '    <div class="container">',
      '      <a href="/" class="logo">My Blog</a>',
      '      <div class="nav-links">',
      '        <a href="/posts">Posts</a>',
      '        <a href="/api/posts">API</a>',
      '      </div>',
      '    </div>',
      '  </nav>',
      '  <main class="container">',
      '    <section class="hero">',
      '      <h1>Welcome to My Blog</h1>',
      '      <p>A blog built with SpeexJS</p>',
      '    </section>',
      '    <section class="posts-preview">',
      '      <h2>Latest Posts</h2>',
      '      <div id="posts-list">',
      '        <p>Loading posts...</p>',
      '      </div>',
      '    </section>',
      '  </main>',
      '  <footer>',
      '    <p>Powered by SpeexJS</p>',
      '  </footer>',
      '  <script>',
      "    fetch('/api/posts')",
      '      .then(r => r.json())',
      '      .then(data => {',
      "        const list = document.getElementById('posts-list')",
      '        if (data.data?.length) {',
      '          list.innerHTML = data.data.map(p => `',
      '            <article class="post-card">',
      '              <h3><a href="/posts/${p.id}">${p.title}</a></h3>',
      '              <p class="meta">${new Date(p.createdAt).toLocaleDateString()}</p>',
      '              <p>${p.excerpt || p.content?.slice(0, 150)}</p>',
      '            </article>',
      "          `).join('')",
      '        } else {',
      "          list.innerHTML = '<p>No posts yet.</p>'",
      '        }',
      '      })',
      '  </script>',
      '</body>',
      '</html>`)',
      '})',
      '',
      "app.get('/posts/:id', async ({ response, params }) => {",
      '  return response.html(`<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="UTF-8" />',
      '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
      '  <title>Post - My Blog</title>',
      '  <link rel="stylesheet" href="/style.css" />',
      '</head>',
      '<body>',
      '  <nav>',
      '    <div class="container">',
      '      <a href="/" class="logo">My Blog</a>',
      '      <div class="nav-links"><a href="/">Home</a></div>',
      '    </div>',
      '  </nav>',
      '  <main class="container">',
      '    <div id="post">',
      '      <p>Loading post...</p>',
      '    </div>',
      '  </main>',
      '  <section class="container" id="comments-section">',
      '    <h3>Comments</h3>',
      '    <div id="comments-list">',
      '      <p>Loading comments...</p>',
      '    </div>',
      '  </section>',
      '  <footer>',
      '    <p>Powered by SpeexJS</p>',
      '  </footer>',
      '  <script>',
      '    const postId = ${params.id}',
      '    Promise.all([',
      "      fetch('/api/posts/' + postId).then(r => r.json()),",
      "      fetch('/api/posts/' + postId + '/comments').then(r => r.json())",
      '    ]).then(([post, comments]) => {',
      '      if (post.data) {',
      "        document.getElementById('post').innerHTML = `",
      '          <h1>${post.data.title}</h1>',
      '          <p class="meta">${new Date(post.data.createdAt).toLocaleDateString()}</p>',
      '          <div class="content">${post.data.content}</div>',
      '        `',
      '      }',
      '      if (comments.data?.length) {',
      "        document.getElementById('comments-list').innerHTML =",
      '          comments.data.map(c => `<div class=\\"comment\\"><p>${c.body}</p><small>${new Date(c.createdAt).toLocaleDateString()}</small></div>`).join(\'\')',
      '      } else {',
      "        document.getElementById('comments-list').innerHTML = '<p>No comments yet.</p>'",
      '      }',
      '    })',
      '  </script>',
      '</body>',
      '</html>`)',
      '})',
      '',
      'export { app }',
    ].join('\n'),
    'src/config/index.ts': [
      'export const Config = {',
      "  port: Number(process.env.PORT ?? '3000'),",
      "  env: process.env.NODE_ENV ?? 'development',",
      "  isDev: (process.env.NODE_ENV ?? 'development') !== 'production',",
      "  isProd: process.env.NODE_ENV === 'production',",
      '}',
    ].join('\n'),
    'src/controllers/post.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Post {',
      '  id: number',
      '  title: string',
      '  slug: string',
      '  content: string',
      '  excerpt: string',
      '  categoryId: number',
      '  tags: string[]',
      '  published: boolean',
      '  createdAt: string',
      '  updatedAt: string',
      '}',
      '',
      'let posts: Post[] = [',
      '  {',
      '    id: 1,',
      "    title: 'Welcome to SpeexJS',",
      "    slug: 'welcome-to-speexjs',",
      "    content: '<p>SpeexJS is a fullstack TypeScript framework with zero dependencies. Build fast, ship faster.</p>',",
      "    excerpt: 'SpeexJS is a fullstack TypeScript framework with zero dependencies.',",
      '    categoryId: 1,',
      "    tags: ['speexjs', 'typescript'],",
      '    published: true,',
      '    createdAt: new Date().toISOString(),',
      '    updatedAt: new Date().toISOString(),',
      '  },',
      ']',
      'let nextId = 2',
      '',
      'const CreatePostSchema = schema.object({',
      '  title: schema.string().min(3).max(200),',
      '  slug: schema.string().min(3).max(200),',
      '  content: schema.string().min(10),',
      '  excerpt: schema.string().max(300).optional(),',
      '  categoryId: schema.number().optional(),',
      '  tags: schema.array(schema.string()).optional(),',
      '  published: schema.boolean().optional(),',
      '})',
      '',
      'export class PostController extends Controller {',
      "  @get('/api/posts')",
      '  async index({ response, query }) {',
      '    const page = Number(query.page) || 1',
      '    const limit = Number(query.limit) || 10',
      '    const offset = (page - 1) * limit',
      '    const published = posts.filter(p => p.published)',
      '    const paginated = published.slice(offset, offset + limit)',
      '    return response.json({',
      '      data: paginated,',
      '      meta: { total: published.length, page, limit, totalPages: Math.ceil(published.length / limit) },',
      '    })',
      '  }',
      '',
      "  @get('/api/posts/:id')",
      '  async show({ response, params }) {',
      '    const post = posts.find(p => p.id === Number(params.id))',
      "    if (!post) return response.status(404).json({ error: 'NOT_FOUND', message: 'Post not found' })",
      '    return response.json({ data: post })',
      '  }',
      '',
      "  @post('/api/posts')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = CreatePostSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const now = new Date().toISOString()',
      '    const post = {',
      '      id: nextId++, ...result.data,',
      '      excerpt: result.data.excerpt || result.data.content.slice(0, 150),',
      '      tags: result.data.tags || [],',
      '      published: result.data.published ?? true,',
      '      categoryId: result.data.categoryId || 1,',
      '      createdAt: now,',
      '      updatedAt: now,',
      '    }',
      '    posts.push(post)',
      '    return response.status(201).json({ data: post })',
      '  }',
      '',
      "  @put('/api/posts/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = posts.findIndex(p => p.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Post not found' })",
      '    const body = await request.body()',
      '    const result = CreatePostSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    posts[idx] = { ...posts[idx], ...result.data, updatedAt: new Date().toISOString() }',
      '    return response.json({ data: posts[idx] })',
      '  }',
      '',
      "  @del('/api/posts/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = posts.findIndex(p => p.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Post not found' })",
      '    posts.splice(idx, 1)',
      "    return response.json({ message: 'Post deleted' })",
      '  }',
      '',
      "  @get('/api/posts/:id/comments')",
      '  async comments({ response, params }) {',
      '    return response.json({ data: comments.filter(c => c.postId === Number(params.id)) })',
      '  }',
      '}',
      '',
      'const comments = [',
      "  { id: 1, postId: 1, author: 'Guest', body: 'Great post! Looking forward to more.', createdAt: new Date().toISOString() },",
      ']',
      'let nextCommentId = 2',
    ].join('\n'),
    'src/controllers/category.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Category { id: number; name: string; slug: string; description: string; createdAt: string }',
      '',
      'let categories = [',
      "  { id: 1, name: 'Technology', slug: 'technology', description: 'Tech posts', createdAt: new Date().toISOString() },",
      "  { id: 2, name: 'Tutorial', slug: 'tutorial', description: 'How-to guides', createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 3',
      '',
      'const CategorySchema = schema.object({',
      '  name: schema.string().min(2).max(100),',
      '  slug: schema.string().min(2).max(100),',
      '  description: schema.string().max(300).optional(),',
      '})',
      '',
      'export class CategoryController extends Controller {',
      "  @get('/api/categories')",
      '  async index({ response }) { return response.json({ data: categories }) }',
      "  @get('/api/categories/:id')",
      '  async show({ response, params }) {',
      '    const cat = categories.find(c => c.id === Number(params.id))',
      "    if (!cat) return response.status(404).json({ error: 'NOT_FOUND', message: 'Category not found' })",
      '    return response.json({ data: cat })',
      '  }',
      "  @post('/api/categories')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = CategorySchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      "    const cat = { id: nextId++, ...result.data, description: result.data.description || '', createdAt: new Date().toISOString() }",
      '    categories.push(cat)',
      '    return response.status(201).json({ data: cat })',
      '  }',
      "  @put('/api/categories/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = categories.findIndex(c => c.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Category not found' })",
      '    const body = await request.body()',
      '    const result = CategorySchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    categories[idx] = { ...categories[idx], ...result.data }',
      '    return response.json({ data: categories[idx] })',
      '  }',
      "  @del('/api/categories/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = categories.findIndex(c => c.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Category not found' })",
      '    categories.splice(idx, 1)',
      "    return response.json({ message: 'Category deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/comment.controller.ts': [
      "import { Controller, get, post, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Comment { id: number; postId: number; author: string; body: string; createdAt: string }',
      '',
      'let comments = [',
      "  { id: 1, postId: 1, author: 'Guest', body: 'Great post!', createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 2',
      '',
      'const CommentSchema = schema.object({',
      '  postId: schema.number(),',
      '  author: schema.string().min(1).max(100),',
      '  body: schema.string().min(1).max(1000),',
      '})',
      '',
      'export class CommentController extends Controller {',
      "  @get('/api/comments')",
      '  async index({ response }) { return response.json({ data: comments }) }',
      "  @post('/api/comments')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = CommentSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const comment = { id: nextId++, ...result.data, createdAt: new Date().toISOString() }',
      '    comments.push(comment)',
      '    return response.status(201).json({ data: comment })',
      '  }',
      "  @del('/api/comments/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = comments.findIndex(c => c.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Comment not found' })",
      '    comments.splice(idx, 1)',
      "    return response.json({ message: 'Comment deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/tag.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Tag { id: number; name: string; slug: string; createdAt: string }',
      '',
      'let tags = [',
      "  { id: 1, name: 'speexjs', slug: 'speexjs', createdAt: new Date().toISOString() },",
      "  { id: 2, name: 'typescript', slug: 'typescript', createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 3',
      '',
      'const TagSchema = schema.object({',
      '  name: schema.string().min(1).max(50),',
      '  slug: schema.string().min(1).max(50),',
      '})',
      '',
      'export class TagController extends Controller {',
      "  @get('/api/tags')",
      '  async index({ response }) { return response.json({ data: tags }) }',
      "  @get('/api/tags/:id')",
      '  async show({ response, params }) {',
      '    const tag = tags.find(t => t.id === Number(params.id))',
      "    if (!tag) return response.status(404).json({ error: 'NOT_FOUND', message: 'Tag not found' })",
      '    return response.json({ data: tag })',
      '  }',
      "  @post('/api/tags')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = TagSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const tag = { id: nextId++, ...result.data, createdAt: new Date().toISOString() }',
      '    tags.push(tag)',
      '    return response.status(201).json({ data: tag })',
      '  }',
      "  @put('/api/tags/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = tags.findIndex(t => t.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Tag not found' })",
      '    const body = await request.body()',
      '    const result = TagSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    tags[idx] = { ...tags[idx], ...result.data }',
      '    return response.json({ data: tags[idx] })',
      '  }',
      "  @del('/api/tags/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = tags.findIndex(t => t.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Tag not found' })",
      '    tags.splice(idx, 1)',
      "    return response.json({ message: 'Tag deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'public/style.css': [
      '* { margin: 0; padding: 0; box-sizing: border-box; }',
      "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }",
      '.container { max-width: 900px; margin: 0 auto; padding: 0 1.5rem; }',
      'nav { background: #1e293b; color: #fff; padding: 1rem 0; margin-bottom: 2rem; }',
      'nav .container { display: flex; justify-content: space-between; align-items: center; }',
      'nav a { color: #fff; text-decoration: none; }',
      '.logo { font-size: 1.25rem; font-weight: 700; }',
      '.nav-links a { margin-left: 1.5rem; color: #94a3b8; }',
      '.nav-links a:hover { color: #fff; }',
      '.hero { text-align: center; padding: 3rem 0; }',
      '.hero h1 { font-size: 2.5rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #3b82f6, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }',
      '.hero p { color: #64748b; font-size: 1.125rem; }',
      '.posts-preview { padding: 2rem 0; }',
      '.posts-preview h2 { margin-bottom: 1.5rem; font-size: 1.5rem; }',
      '.post-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem; }',
      '.post-card h3 { margin-bottom: 0.5rem; }',
      '.post-card h3 a { color: #1e293b; text-decoration: none; }',
      '.post-card h3 a:hover { color: #3b82f6; }',
      '.post-card .meta { color: #94a3b8; font-size: 0.875rem; margin-bottom: 0.75rem; }',
      'footer { text-align: center; padding: 2rem; color: #94a3b8; margin-top: 3rem; border-top: 1px solid #e2e8f0; }',
      '.content { font-size: 1.125rem; line-height: 1.8; }',
      '.comment { background: #f1f5f9; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; }',
      '.comment small { color: #94a3b8; }',
    ].join('\n'),
    '.env.example': ['PORT=3000', 'NODE_ENV=development'].join('\n'),
    '.gitignore': ['node_modules/', 'dist/', '.env', '*.log'].join('\n'),
    'biome.json': JSON.stringify(
      {
        $schema: 'https://biomejs.dev/schemas/1.9.0/schema.json',
        organizeImports: { enabled: true },
        linter: { enabled: true, rules: { recommended: true } },
        formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineEnding: 'lf' },
      },
      null,
      2,
    ),
  },
}
