const PKG_DEPS = { speexjs: 'latest' }
const PKG_DEVDEPS = { '@types/node': '^26.0.1', tsx: '^4.19.0', typescript: '^5.7.0' }

function pkg(name, scripts, extra = {}) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      type: 'module',
      private: true,
      scripts,
      dependencies: PKG_DEPS,
      devDependencies: { ...PKG_DEVDEPS, ...extra.devDependencies },
      ...extra,
    },
    null,
    2,
  )
}

function tsconfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        declaration: true,
        sourceMap: true,
        esModuleInterop: true,
        isolatedModules: true,
        resolveJsonModule: true,
        outDir: './dist',
        rootDir: './src',
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['src/**/*.ts'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  )
}

export const ecommerceTemplate = {
  dirs: ['src/config', 'src/controllers', 'src/models', 'src/middleware', 'src/views', 'public', 'public/images'],
  files: {
    'package.json': (name) =>
      pkg(name, {
        dev: 'speexjs serve',
        build: 'speexjs build',
        start: 'node dist/index.js',
        lint: 'tsc --noEmit',
      }),
    'tsconfig.json': tsconfig(),
    'src/index.ts': [
      "import { speexjs, cors, bodyParser, staticFiles } from 'speexjs/server'",
      "import { ProductController } from './controllers/product.controller.js'",
      "import { CartController } from './controllers/cart.controller.js'",
      "import { OrderController } from './controllers/order.controller.js'",
      "import { PaymentController } from './controllers/payment.controller.js'",
      "import { CategoryController } from './controllers/category.controller.js'",
      '',
      'const app = speexjs()',
      '',
      'app.use(cors())',
      'app.use(bodyParser())',
      "app.use(staticFiles('public', { maxAge: 86400 }))",
      '',
      'app.controller(ProductController)',
      'app.controller(CartController)',
      'app.controller(OrderController)',
      'app.controller(PaymentController)',
      'app.controller(CategoryController)',
      '',
      "app.get('/', async ({ response }) => {",
      '  return response.html([',
      "    '<!DOCTYPE html>'",
      '    \'<html lang="en">\'',
      '    \'<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>SpeexShop</title><link rel="stylesheet" href="/style.css" /></head>\'',
      "    '<body>'",
      '    \'<nav><div class="container"><a href="/" class="logo">SpeexShop</a><div class="nav-links"><a href="/cart">Cart</a><a href="/api/products">API</a></div></div></nav>\'',
      '    \'<main class="container">\'',
      '    \'<section class="hero"><h1>Welcome to SpeexShop</h1><p>Your ecommerce platform built with SpeexJS</p></section>\'',
      '    \'<section class="products"><h2>Featured Products</h2><div id="products-grid" class="product-grid"><p>Loading products...</p></div></section>\'',
      "    '</main>'",
      "    '<footer><p>Powered by SpeexJS</p></footer>'",
      '    \'<script>fetch("/api/products").then(r=>r.json()).then(data=>{const grid=document.getElementById("products-grid");if(data.data?.length){grid.innerHTML="<p>"+data.data.length+" products loaded</p>"}else{grid.innerHTML="<p>No products yet.</p>"}});function addToCart(id){fetch("/api/cart/add",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:id,quantity:1})}).then(r=>r.json()).then(()=>alert("Added to cart!"))}',
      "    '</script>'",
      "    '</body></html>'",
      "  ].join('\n'))",
      '})',
      '',
      "app.get('/cart', async ({ response }) => {",
      '  return response.html([',
      "    '<!DOCTYPE html>'",
      '    \'<html lang="en">\'',
      '    \'<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Cart - SpeexShop</title><link rel="stylesheet" href="/style.css" /></head>\'',
      "    '<body>'",
      '    \'<nav><div class="container"><a href="/" class="logo">SpeexShop</a><div class="nav-links"><a href="/">Home</a></div></div></nav>\'',
      '    \'<main class="container"><h1>Shopping Cart</h1><div id="cart"><p>Loading cart...</p></div></main>\'',
      '    \'<script>fetch("/api/cart").then(r=>r.json()).then(data=>{const c=document.getElementById("cart");if(data.data?.items?.length){c.innerHTML="<p>"+data.data.items.length+" items in cart</p>"}else{c.innerHTML="<p>Your cart is empty.</p>"}});function checkout(){fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})}).then(r=>r.json()).then(d=>{alert("Order placed! ID: "+d.data?.id);location.reload()})}',
      "    '</script>'",
      "    '</body></html>'",
      "  ].join('\n'))",
      '})',
      '',
      'export { app }',
    ].join('\n'),
    'src/config/index.ts': [
      'export const Config = {',
      "  port: Number(process.env.PORT ?? '3000'),",
      "  env: process.env.NODE_ENV ?? 'development',",
      "  isDev: (process.env.NODE_ENV ?? 'development') !== 'production',",
      "  isProd: process.env.NODE_ENV === 'production',",
      "  currency: 'USD',",
      '  taxRate: 0.08,',
      "  stripeKey: process.env.STRIPE_KEY ?? '',",
      '}',
    ].join('\n'),
    'src/controllers/product.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Product { id: number; name: string; slug: string; description: string; price: number; compareAtPrice: number | null; imageUrl: string; imageColor: string; categoryId: number; inventory: number; sku: string; published: boolean; createdAt: string; updatedAt: string }',
      '',
      'let products = [',
      "  { id: 1, name: 'Wireless Headphones', slug: 'wireless-headphones', description: 'Premium wireless headphones with noise cancellation.', price: 7999, compareAtPrice: 9999, imageUrl: '', imageColor: '#3b82f6', categoryId: 1, inventory: 50, sku: 'WH-001', published: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },",
      "  { id: 2, name: 'Smart Watch', slug: 'smart-watch', description: 'Fitness tracker with heart rate monitor.', price: 19999, compareAtPrice: null, imageUrl: '', imageColor: '#8b5cf6', categoryId: 1, inventory: 30, sku: 'SW-002', published: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },",
      "  { id: 3, name: 'USB-C Hub', slug: 'usb-c-hub', description: '7-in-1 USB-C hub with HDMI, SD card, and USB 3.0.', price: 3499, compareAtPrice: 4499, imageUrl: '', imageColor: '#10b981', categoryId: 2, inventory: 100, sku: 'UC-003', published: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },",
      ']',
      'let nextId = 4',
      '',
      'const ProductSchema = schema.object({',
      '  name: schema.string().min(2).max(200),',
      '  slug: schema.string().min(2).max(200),',
      '  description: schema.string().max(2000).optional(),',
      '  price: schema.number().min(0),',
      '  compareAtPrice: schema.number().optional().nullable(),',
      '  imageUrl: schema.string().optional(),',
      '  categoryId: schema.number(),',
      '  inventory: schema.number().min(0),',
      '  sku: schema.string().min(1).max(50),',
      '  published: schema.boolean().optional(),',
      '})',
      '',
      'export class ProductController extends Controller {',
      "  @get('/api/products')",
      '  async index({ response, query }) {',
      '    const page = Number(query.page) || 1',
      '    const limit = Number(query.limit) || 20',
      '    const offset = (page - 1) * limit',
      '    const categoryId = query.categoryId ? Number(query.categoryId) : undefined',
      '    let filtered = products.filter(p => p.published)',
      '    if (categoryId) filtered = filtered.filter(p => p.categoryId === categoryId)',
      '    const paginated = filtered.slice(offset, offset + limit)',
      '    return response.json({',
      '      data: paginated,',
      '      meta: { total: filtered.length, page, limit, totalPages: Math.ceil(filtered.length / limit) },',
      '    })',
      '  }',
      '',
      "  @get('/api/products/:id')",
      '  async show({ response, params }) {',
      '    const product = products.find(p => p.id === Number(params.id))',
      "    if (!product) return response.status(404).json({ error: 'NOT_FOUND', message: 'Product not found' })",
      '    return response.json({ data: product })',
      '  }',
      '',
      "  @post('/api/products')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = ProductSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const now = new Date().toISOString()',
      '    const product = {',
      '      id: nextId++, ...result.data,',
      "      description: result.data.description || '',",
      '      compareAtPrice: result.data.compareAtPrice ?? null,',
      "      imageUrl: result.data.imageUrl || '',",
      "      imageColor: '#e2e8f0',",
      '      published: result.data.published ?? true,',
      '      createdAt: now, updatedAt: now,',
      '    }',
      '    products.push(product)',
      '    return response.status(201).json({ data: product })',
      '  }',
      '',
      "  @put('/api/products/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = products.findIndex(p => p.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Product not found' })",
      '    const body = await request.body()',
      '    const result = ProductSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    products[idx] = { ...products[idx], ...result.data, updatedAt: new Date().toISOString() }',
      '    return response.json({ data: products[idx] })',
      '  }',
      '',
      "  @del('/api/products/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = products.findIndex(p => p.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Product not found' })",
      '    products.splice(idx, 1)',
      "    return response.json({ message: 'Product deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/cart.controller.ts': [
      "import { Controller, get, post, del } from 'speexjs/server'",
      '',
      'export const carts = new Map()',
      '',
      'const products = [',
      "  { id: 1, name: 'Wireless Headphones', price: 7999 },",
      "  { id: 2, name: 'Smart Watch', price: 19999 },",
      "  { id: 3, name: 'USB-C Hub', price: 3499 },",
      ']',
      '',
      'export class CartController extends Controller {',
      '  getOrCreateCart(sessionId) {',
      '    if (!carts.has(sessionId)) {',
      '      carts.set(sessionId, { id: sessionId, items: [], total: 0, createdAt: new Date().toISOString() })',
      '    }',
      '    return carts.get(sessionId)',
      '  }',
      '',
      "  @get('/api/cart')",
      '  async show({ request, response }) {',
      "    const sessionId = request.headers.get('x-session-id') || 'default'",
      '    const cart = this.getOrCreateCart(sessionId)',
      '    return response.json({ data: cart })',
      '  }',
      '',
      "  @post('/api/cart/add')",
      '  async add({ request, response }) {',
      '    const body = await request.body()',
      '    const productId = Number(body.productId)',
      '    const quantity = Number(body.quantity) || 1',
      "    const sessionId = request.headers.get('x-session-id') || 'default'",
      '    const cart = this.getOrCreateCart(sessionId)',
      '',
      '    const product = products.find(p => p.id === productId)',
      "    if (!product) return response.status(404).json({ error: 'NOT_FOUND', message: 'Product not found' })",
      '',
      '    const existing = cart.items.find(i => i.productId === productId)',
      '    if (existing) {',
      '      existing.quantity += quantity',
      '    } else {',
      '      cart.items.push({ productId, name: product.name, price: product.price, quantity })',
      '    }',
      '',
      '    cart.total = cart.items.reduce((sum, i) => sum + i.price * i.quantity, 0)',
      '    return response.json({ data: cart })',
      '  }',
      '',
      "  @post('/api/cart/update')",
      '  async update({ request, response }) {',
      '    const body = await request.body()',
      '    const productId = Number(body.productId)',
      '    const quantity = Number(body.quantity)',
      "    const sessionId = request.headers.get('x-session-id') || 'default'",
      '    const cart = this.getOrCreateCart(sessionId)',
      '',
      '    if (quantity <= 0) {',
      '      cart.items = cart.items.filter(i => i.productId !== productId)',
      '    } else {',
      '      const item = cart.items.find(i => i.productId === productId)',
      '      if (item) item.quantity = quantity',
      '    }',
      '',
      '    cart.total = cart.items.reduce((sum, i) => sum + i.price * i.quantity, 0)',
      '    return response.json({ data: cart })',
      '  }',
      '',
      "  @del('/api/cart')",
      '  async clear({ request, response }) {',
      "    const sessionId = request.headers.get('x-session-id') || 'default'",
      '    carts.delete(sessionId)',
      "    return response.json({ message: 'Cart cleared' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/order.controller.ts': [
      "import { Controller, get, post } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      "import { carts } from './cart.controller.js'",
      '',
      'interface Order { id: number; items: any[]; subtotal: number; tax: number; total: number; status: string; shippingAddress: string; email: string; createdAt: string; updatedAt: string }',
      '',
      'let orders = []',
      'let nextId = 1',
      '',
      'const OrderSchema = schema.object({',
      '  shippingAddress: schema.string().min(5).max(500),',
      '  email: schema.string().email(),',
      '})',
      '',
      'export class OrderController extends Controller {',
      "  @get('/api/orders')",
      '  async index({ response }) { return response.json({ data: orders }) }',
      '',
      "  @get('/api/orders/:id')",
      '  async show({ response, params }) {',
      '    const order = orders.find(o => o.id === Number(params.id))',
      "    if (!order) return response.status(404).json({ error: 'NOT_FOUND', message: 'Order not found' })",
      '    return response.json({ data: order })',
      '  }',
      '',
      "  @post('/api/orders')",
      '  async create({ request, response }) {',
      '    const body = await request.body()',
      "    const sessionId = request.headers.get('x-session-id') || 'default'",
      '',
      '    const cart = carts.get(sessionId)',
      '    if (!cart || !cart.items?.length) {',
      "      return response.status(400).json({ error: 'BAD_REQUEST', message: 'Cart is empty' })",
      '    }',
      '',
      '    const result = OrderSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '',
      '    const subtotal = cart.total',
      '    const tax = Math.round(subtotal * 0.08)',
      '    const now = new Date().toISOString()',
      '',
      '    const order = {',
      '      id: nextId++,',
      '      items: [...cart.items],',
      '      subtotal, tax,',
      '      total: subtotal + tax,',
      "      status: 'pending',",
      '      shippingAddress: result.data.shippingAddress,',
      '      email: result.data.email,',
      '      createdAt: now, updatedAt: now,',
      '    }',
      '    orders.push(order)',
      '    carts.delete(sessionId)',
      '    return response.status(201).json({ data: order })',
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/payment.controller.ts': [
      "import { Controller, get, post } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Payment { id: number; orderId: number; amount: number; currency: string; method: string; status: string; transactionId: string; createdAt: string }',
      '',
      'let payments = []',
      'let nextId = 1',
      '',
      'const PaymentSchema = schema.object({',
      '  orderId: schema.number(),',
      '  amount: schema.number().min(0),',
      "  method: schema.enum(['card', 'bank_transfer', 'paypal']),",
      '})',
      '',
      'export class PaymentController extends Controller {',
      "  @get('/api/payments')",
      '  async index({ response }) { return response.json({ data: payments }) }',
      '',
      "  @get('/api/payments/:id')",
      '  async show({ response, params }) {',
      '    const payment = payments.find(p => p.id === Number(params.id))',
      "    if (!payment) return response.status(404).json({ error: 'NOT_FOUND', message: 'Payment not found' })",
      '    return response.json({ data: payment })',
      '  }',
      '',
      "  @post('/api/payments')",
      '  async process({ request, response }) {',
      '    const body = await request.body()',
      '    const result = PaymentSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const now = new Date().toISOString()',
      '    const payment = {',
      '      id: nextId++,',
      '      orderId: result.data.orderId,',
      '      amount: result.data.amount,',
      "      currency: 'USD',",
      '      method: result.data.method,',
      "      status: 'completed',",
      "      transactionId: 'txn_' + Date.now() + '_' + nextId,",
      '      createdAt: now,',
      '    }',
      '    payments.push(payment)',
      '    return response.status(201).json({ data: payment })',
      '  }',
      '',
      "  @post('/api/payments/:id/refund')",
      '  async refund({ response, params }) {',
      '    const idx = payments.findIndex(p => p.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Payment not found' })",
      "    if (payments[idx].status !== 'completed') {",
      "      return response.status(400).json({ error: 'BAD_REQUEST', message: 'Payment cannot be refunded' })",
      '    }',
      "    payments[idx] = { ...payments[idx], status: 'refunded' }",
      '    return response.json({ data: payments[idx] })',
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/category.controller.ts': [
      "import { Controller, get } from 'speexjs/server'",
      '',
      'const categories = [',
      "  { id: 1, name: 'Electronics', slug: 'electronics', productCount: 2 },",
      "  { id: 2, name: 'Accessories', slug: 'accessories', productCount: 1 },",
      "  { id: 3, name: 'Clothing', slug: 'clothing', productCount: 0 },",
      ']',
      '',
      'export class CategoryController extends Controller {',
      "  @get('/api/categories')",
      '  async index({ response }) { return response.json({ data: categories }) }',
      '',
      "  @get('/api/categories/:id')",
      '  async show({ response, params }) {',
      '    const cat = categories.find(c => c.id === Number(params.id))',
      "    if (!cat) return response.status(404).json({ error: 'NOT_FOUND', message: 'Category not found' })",
      '    return response.json({ data: cat })',
      '  }',
      '}',
    ].join('\n'),
    'public/style.css': [
      '* { margin: 0; padding: 0; box-sizing: border-box; }',
      "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }",
      '.container { max-width: 1100px; margin: 0 auto; padding: 0 1.5rem; }',
      'nav { background: #1e293b; color: #fff; padding: 1rem 0; margin-bottom: 2rem; }',
      'nav .container { display: flex; justify-content: space-between; align-items: center; }',
      'nav a { color: #fff; text-decoration: none; }',
      '.logo { font-size: 1.25rem; font-weight: 700; }',
      '.nav-links a { margin-left: 1.5rem; color: #94a3b8; }',
      '.nav-links a:hover { color: #fff; }',
      '.hero { text-align: center; padding: 3rem 0; }',
      '.hero h1 { font-size: 2.5rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #3b82f6, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }',
      '.hero p { color: #64748b; font-size: 1.125rem; }',
      '.products { padding: 2rem 0; }',
      '.products h2 { margin-bottom: 1.5rem; font-size: 1.5rem; }',
      '.product-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1.5rem; }',
      '.product-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 1.5rem; text-align: center; }',
      '.product-image { height: 160px; border-radius: 8px; margin-bottom: 1rem; }',
      '.product-card h3 { font-size: 1.125rem; margin-bottom: 0.5rem; }',
      '.price { font-size: 1.25rem; font-weight: 700; color: #3b82f6; margin-bottom: 0.5rem; }',
      '.desc { color: #64748b; font-size: 0.875rem; margin-bottom: 1rem; }',
      '.product-card button { background: #3b82f6; color: #fff; border: none; padding: 0.75rem 1.5rem; border-radius: 6px; cursor: pointer; font-size: 0.875rem; }',
      '.product-card button:hover { background: #2563eb; }',
      '.cart-item { display: flex; justify-content: space-between; padding: 1rem; border-bottom: 1px solid #e2e8f0; }',
      '.cart-total { text-align: right; padding: 1rem; font-size: 1.125rem; }',
      'button { background: #3b82f6; color: #fff; border: none; padding: 0.75rem 1.5rem; border-radius: 6px; cursor: pointer; font-size: 1rem; margin-top: 1rem; }',
      'button:hover { background: #2563eb; }',
      'footer { text-align: center; padding: 2rem; color: #94a3b8; margin-top: 3rem; border-top: 1px solid #e2e8f0; }',
    ].join('\n'),
    '.env.example': ['PORT=3000', 'NODE_ENV=development', 'STRIPE_KEY='].join('\n'),
    '.gitignore': ['node_modules/', 'dist/', '.env', '*.log'].join('\n'),
    'biome.json': JSON.stringify(
      {
        $schema: 'https://biomejs.dev/schemas/1.9.0/schema.json',
        organizeImports: { enabled: true },
        linter: { enabled: true, rules: { recommended: true } },
        formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineEnding: 'lf' },
      },
      null,
      2,
    ),
  },
}
