const PKG_DEPS = { speexjs: 'latest' }
const PKG_DEVDEPS = { '@types/node': '^26.0.1', tsx: '^4.19.0', typescript: '^5.7.0' }

function pkg(name, scripts, extra = {}) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      type: 'module',
      private: true,
      scripts,
      dependencies: PKG_DEPS,
      devDependencies: { ...PKG_DEVDEPS, ...extra.devDependencies },
      ...extra,
    },
    null,
    2,
  )
}

function tsconfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        declaration: true,
        sourceMap: true,
        esModuleInterop: true,
        isolatedModules: true,
        resolveJsonModule: true,
        outDir: './dist',
        rootDir: './src',
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['src/**/*.ts'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  )
}

export const saasTemplate = {
  dirs: ['src/config', 'src/controllers', 'src/models', 'src/middleware', 'src/views', 'public'],
  files: {
    'package.json': (name) =>
      pkg(name, {
        dev: 'speexjs serve',
        build: 'speexjs build',
        start: 'node dist/index.js',
        lint: 'tsc --noEmit',
      }),
    'tsconfig.json': tsconfig(),
    'src/index.ts': [
      "import { speexjs, cors, bodyParser } from 'speexjs/server'",
      "import { TeamController } from './controllers/team.controller.js'",
      "import { UserController } from './controllers/user.controller.js'",
      "import { RoleController } from './controllers/role.controller.js'",
      "import { BillingController } from './controllers/billing.controller.js'",
      "import { SubscriptionController } from './controllers/subscription.controller.js'",
      '',
      'const app = speexjs()',
      '',
      'app.use(cors())',
      'app.use(bodyParser())',
      '',
      'app.controller(TeamController)',
      'app.controller(UserController)',
      'app.controller(RoleController)',
      'app.controller(BillingController)',
      'app.controller(SubscriptionController)',
      '',
      "app.get('/', async ({ response }) => {",
      '  return response.json({',
      "    name: 'SaaS App',",
      "    version: '0.1.0',",
      '    endpoints: {',
      "      teams: '/api/teams',",
      "      users: '/api/users',",
      "      roles: '/api/roles',",
      "      billing: '/api/billing',",
      "      subscriptions: '/api/subscriptions',",
      '    },',
      '  })',
      '})',
      '',
      'export { app }',
    ].join('\n'),
    'src/config/index.ts': [
      'export const Config = {',
      "  port: Number(process.env.PORT ?? '3000'),",
      "  env: process.env.NODE_ENV ?? 'development',",
      "  isDev: (process.env.NODE_ENV ?? 'development') !== 'production',",
      "  isProd: process.env.NODE_ENV === 'production',",
      "  appKey: process.env.APP_KEY ?? '',",
      "  stripeKey: process.env.STRIPE_KEY ?? '',",
      '}',
    ].join('\n'),
    'src/controllers/team.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Team { id: number; name: string; slug: string; ownerId: number; memberCount: number; plan: string; createdAt: string; updatedAt: string }',
      '',
      'let teams = [',
      "  { id: 1, name: 'Acme Corp', slug: 'acme-corp', ownerId: 1, memberCount: 3, plan: 'pro', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },",
      ']',
      'let nextId = 2',
      '',
      'const TeamSchema = schema.object({',
      '  name: schema.string().min(2).max(100),',
      '  slug: schema.string().min(2).max(100),',
      '  ownerId: schema.number(),',
      "  plan: schema.enum(['free', 'pro', 'enterprise']).optional(),",
      '})',
      '',
      'export class TeamController extends Controller {',
      "  @get('/api/teams')",
      '  async index({ response }) { return response.json({ data: teams }) }',
      "  @get('/api/teams/:id')",
      '  async show({ response, params }) {',
      '    const team = teams.find(t => t.id === Number(params.id))',
      "    if (!team) return response.status(404).json({ error: 'NOT_FOUND', message: 'Team not found' })",
      '    return response.json({ data: team })',
      '  }',
      "  @post('/api/teams')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = TeamSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const now = new Date().toISOString()',
      "    const team = { id: nextId++, ...result.data, plan: result.data.plan || 'free', memberCount: 1, createdAt: now, updatedAt: now }",
      '    teams.push(team)',
      '    return response.status(201).json({ data: team })',
      '  }',
      "  @put('/api/teams/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = teams.findIndex(t => t.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Team not found' })",
      '    const body = await request.body()',
      '    const result = TeamSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    teams[idx] = { ...teams[idx], ...result.data, updatedAt: new Date().toISOString() }',
      '    return response.json({ data: teams[idx] })',
      '  }',
      "  @del('/api/teams/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = teams.findIndex(t => t.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Team not found' })",
      '    teams.splice(idx, 1)',
      "    return response.json({ message: 'Team deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/user.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface User { id: number; name: string; email: string; role: string; teamId: number; avatar: string; createdAt: string }',
      '',
      'let users = [',
      "  { id: 1, name: 'Admin User', email: 'admin@acme.com', role: 'admin', teamId: 1, avatar: '', createdAt: new Date().toISOString() },",
      "  { id: 2, name: 'Jane Member', email: 'jane@acme.com', role: 'member', teamId: 1, avatar: '', createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 3',
      '',
      'const UserSchema = schema.object({',
      '  name: schema.string().min(2).max(100),',
      '  email: schema.string().email(),',
      "  role: schema.enum(['admin', 'member', 'viewer']).optional(),",
      '  teamId: schema.number(),',
      '})',
      '',
      'export class UserController extends Controller {',
      "  @get('/api/users')",
      '  async index({ response, query }) {',
      '    const teamId = query.teamId ? Number(query.teamId) : undefined',
      '    const filtered = teamId ? users.filter(u => u.teamId === teamId) : users',
      '    return response.json({ data: filtered })',
      '  }',
      "  @get('/api/users/:id')",
      '  async show({ response, params }) {',
      '    const user = users.find(u => u.id === Number(params.id))',
      "    if (!user) return response.status(404).json({ error: 'NOT_FOUND', message: 'User not found' })",
      '    return response.json({ data: user })',
      '  }',
      "  @post('/api/users')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = UserSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      "    const user = { id: nextId++, ...result.data, role: result.data.role || 'member', avatar: '', createdAt: new Date().toISOString() }",
      '    users.push(user)',
      '    return response.status(201).json({ data: user })',
      '  }',
      "  @put('/api/users/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = users.findIndex(u => u.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'User not found' })",
      '    const body = await request.body()',
      '    const result = UserSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    users[idx] = { ...users[idx], ...result.data }',
      '    return response.json({ data: users[idx] })',
      '  }',
      "  @del('/api/users/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = users.findIndex(u => u.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'User not found' })",
      '    users.splice(idx, 1)',
      "    return response.json({ message: 'User deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/role.controller.ts': [
      "import { Controller, get, post, put, del } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Role { id: number; name: string; slug: string; permissions: string[]; teamId: number; createdAt: string }',
      '',
      'let roles = [',
      "  { id: 1, name: 'Admin', slug: 'admin', permissions: ['read', 'write', 'delete', 'manage'], teamId: 1, createdAt: new Date().toISOString() },",
      "  { id: 2, name: 'Member', slug: 'member', permissions: ['read', 'write'], teamId: 1, createdAt: new Date().toISOString() },",
      "  { id: 3, name: 'Viewer', slug: 'viewer', permissions: ['read'], teamId: 1, createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 4',
      '',
      'const RoleSchema = schema.object({',
      '  name: schema.string().min(2).max(50),',
      '  slug: schema.string().min(2).max(50),',
      '  permissions: schema.array(schema.string()),',
      '  teamId: schema.number(),',
      '})',
      '',
      'export class RoleController extends Controller {',
      "  @get('/api/roles')",
      '  async index({ response, query }) {',
      '    const teamId = query.teamId ? Number(query.teamId) : undefined',
      '    const filtered = teamId ? roles.filter(r => r.teamId === teamId) : roles',
      '    return response.json({ data: filtered })',
      '  }',
      "  @get('/api/roles/:id')",
      '  async show({ response, params }) {',
      '    const role = roles.find(r => r.id === Number(params.id))',
      "    if (!role) return response.status(404).json({ error: 'NOT_FOUND', message: 'Role not found' })",
      '    return response.json({ data: role })',
      '  }',
      "  @post('/api/roles')",
      '  async store({ request, response }) {',
      '    const body = await request.body()',
      '    const result = RoleSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    const role = { id: nextId++, ...result.data, createdAt: new Date().toISOString() }',
      '    roles.push(role)',
      '    return response.status(201).json({ data: role })',
      '  }',
      "  @put('/api/roles/:id')",
      '  async update({ request, response, params }) {',
      '    const idx = roles.findIndex(r => r.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Role not found' })",
      '    const body = await request.body()',
      '    const result = RoleSchema.safeParse(body)',
      "    if (!result.success) return response.status(422).json({ error: 'VALIDATION_ERROR', message: result.error })",
      '    roles[idx] = { ...roles[idx], ...result.data }',
      '    return response.json({ data: roles[idx] })',
      '  }',
      "  @del('/api/roles/:id')",
      '  async destroy({ response, params }) {',
      '    const idx = roles.findIndex(r => r.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Role not found' })",
      '    roles.splice(idx, 1)',
      "    return response.json({ message: 'Role deleted' })",
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/billing.controller.ts': [
      "import { Controller, get, post } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'interface Invoice { id: number; teamId: number; amount: number; currency: string; status: string; description: string; dueDate: string; paidAt: string | null; createdAt: string }',
      '',
      'let invoices = [',
      "  { id: 1, teamId: 1, amount: 2999, currency: 'USD', status: 'paid', description: 'Pro Plan - Monthly', dueDate: new Date().toISOString(), paidAt: new Date().toISOString(), createdAt: new Date().toISOString() },",
      ']',
      'let nextId = 2',
      '',
      'export class BillingController extends Controller {',
      "  @get('/api/billing/invoices')",
      '  async index({ response, query }) {',
      '    const teamId = query.teamId ? Number(query.teamId) : undefined',
      '    const filtered = teamId ? invoices.filter(i => i.teamId === teamId) : invoices',
      '    return response.json({ data: filtered })',
      '  }',
      "  @get('/api/billing/invoices/:id')",
      '  async show({ response, params }) {',
      '    const invoice = invoices.find(i => i.id === Number(params.id))',
      "    if (!invoice) return response.status(404).json({ error: 'NOT_FOUND', message: 'Invoice not found' })",
      '    return response.json({ data: invoice })',
      '  }',
      "  @get('/api/billing/usage')",
      '  async usage({ response, query }) {',
      '    const teamId = Number(query.teamId) || 1',
      '    return response.json({',
      '      data: {',
      '        teamId,',
      '        apiCalls: { used: 15234, limit: 50000 },',
      "        storage: { used: '2.3 GB', limit: '10 GB' },",
      '        seats: { used: 3, limit: 10 },',
      '        period: { start: new Date(Date.now() - 2592000000).toISOString(), end: new Date().toISOString() },',
      '      },',
      '    })',
      '  }',
      '}',
    ].join('\n'),
    'src/controllers/subscription.controller.ts': [
      "import { Controller, get, post, put } from 'speexjs/server'",
      "import { schema } from 'speexjs/schema'",
      '',
      'const plans = [',
      "  { id: 1, name: 'Free', slug: 'free', price: 0, currency: 'USD', interval: 'month', features: ['3 members', '1GB storage', 'Basic support'], popular: false },",
      "  { id: 2, name: 'Pro', slug: 'pro', price: 2999, currency: 'USD', interval: 'month', features: ['10 members', '10GB storage', 'Priority support', 'API access'], popular: true },",
      "  { id: 3, name: 'Enterprise', slug: 'enterprise', price: 99900, currency: 'USD', interval: 'month', features: ['Unlimited members', '100GB storage', 'Dedicated support', 'Custom integrations', 'SLA'], popular: false },",
      ']',
      '',
      'let subscriptions = [',
      "  { id: 1, teamId: 1, planId: 2, status: 'active', trialEndsAt: '', currentPeriodStart: new Date().toISOString(), currentPeriodEnd: new Date(Date.now() + 2592000000).toISOString(), createdAt: new Date().toISOString() },",
      ']',
      'let nextSubId = 2',
      '',
      'export class SubscriptionController extends Controller {',
      "  @get('/api/subscriptions/plans')",
      '  async plans({ response }) { return response.json({ data: plans }) }',
      "  @get('/api/subscriptions')",
      '  async index({ response, query }) {',
      '    const teamId = Number(query.teamId) || 1',
      '    const subs = subscriptions.filter(s => s.teamId === teamId)',
      '    return response.json({ data: subs })',
      '  }',
      "  @post('/api/subscriptions')",
      '  async create({ request, response }) {',
      '    const body = await request.body()',
      '    const now = new Date().toISOString()',
      '    const sub = {',
      '      id: nextSubId++,',
      '      teamId: Number(body.teamId) || 1,',
      '      planId: Number(body.planId) || 2,',
      "      status: 'trialing',",
      '      trialEndsAt: new Date(Date.now() + 1209600000).toISOString(),',
      '      currentPeriodStart: now,',
      '      currentPeriodEnd: new Date(Date.now() + 2592000000).toISOString(),',
      '      createdAt: now,',
      '    }',
      '    subscriptions.push(sub)',
      '    return response.status(201).json({ data: sub })',
      '  }',
      "  @put('/api/subscriptions/:id/cancel')",
      '  async cancel({ response, params }) {',
      '    const idx = subscriptions.findIndex(s => s.id === Number(params.id))',
      "    if (idx === -1) return response.status(404).json({ error: 'NOT_FOUND', message: 'Subscription not found' })",
      "    subscriptions[idx] = { ...subscriptions[idx], status: 'canceled' }",
      '    return response.json({ data: subscriptions[idx] })',
      '  }',
      '}',
    ].join('\n'),
    'src/middleware/auth.middleware.ts': [
      "import type { RouteContext } from 'speexjs/server/router'",
      '',
      'export function requireRole(...roles) {',
      '  return async (ctx, next) => {',
      "    const token = ctx.request.headers.get('authorization')",
      '    if (!token) {',
      "      ctx.response.status(401).json({ error: 'UNAUTHORIZED', message: 'Missing authorization header' })",
      '      return',
      '    }',
      '    if (roles.length > 0) {',
      "      const userRole = ctx.request.headers.get('x-user-role') || 'member'",
      '      if (!roles.includes(userRole)) {',
      "        ctx.response.status(403).json({ error: 'FORBIDDEN', message: 'Insufficient permissions' })",
      '        return',
      '      }',
      '    }',
      '    await next()',
      '  }',
      '}',
    ].join('\n'),
    '.env.example': ['PORT=3000', 'NODE_ENV=development', 'APP_KEY=', 'STRIPE_KEY='].join('\n'),
    '.gitignore': ['node_modules/', 'dist/', '.env', '*.log'].join('\n'),
    'biome.json': JSON.stringify(
      {
        $schema: 'https://biomejs.dev/schemas/1.9.0/schema.json',
        organizeImports: { enabled: true },
        linter: { enabled: true, rules: { recommended: true } },
        formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineEnding: 'lf' },
      },
      null,
      2,
    ),
  },
}
