import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { colors } from '../../native/colors.js'

interface SdkGenOptions {
  output?: string
  name?: string
  format?: string
}

interface ParsedRoute {
  method: string
  path: string
  tag: string
  params: ParamInfo[]
}

interface ParamInfo {
  name: string
  type: string
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function singularize(word: string): string {
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y'
  if (word.endsWith('ses')) return word.slice(0, -3)
  if (word.endsWith('s')) return word.slice(0, -1)
  return word
}

function extractPathParams(path: string): ParamInfo[] {
  const params: ParamInfo[] = []
  const regex = /:(\w+)/g
  let match: RegExpExecArray | null
  while ((match = regex.exec(path)) !== null) {
    const name = match[1]
    if (name) {
      const type = name === 'id' || name.endsWith('Id') || name.endsWith('_id') ? 'number' : 'string'
      params.push({ name, type })
    }
  }
  return params
}

function scanControllers(): ParsedRoute[] {
  const routesDir = resolve(process.cwd(), 'src/server/controllers')
  const allRoutes: ParsedRoute[] = []

  if (!existsSync(routesDir)) return allRoutes

  const files = readdirSync(routesDir).filter((f) => f.endsWith('.ts'))
  const pattern = /@(get|post|put|patch|del|delete)\s*\(\s*'([^']+)'\s*\)/g

  for (const file of files) {
    const content = readFileSync(resolve(routesDir, file), 'utf-8')
    const tag = file.replace('.controller.ts', '').replace('.ts', '')
    let match: RegExpExecArray | null
    while ((match = pattern.exec(content)) !== null) {
      const methodStr = match[1]
      const path = match[2] || ''
      if (!methodStr || !path) continue
      const method = methodStr === 'del' ? 'DELETE' : methodStr.toUpperCase()
      allRoutes.push({
        method,
        path,
        tag,
        params: extractPathParams(path),
      })
    }
  }

  return allRoutes
}

function parseSpecIntoRoutes(spec: Record<string, unknown>): ParsedRoute[] {
  const routes: ParsedRoute[] = []
  const paths = spec.paths as Record<string, Record<string, unknown>> | undefined
  if (!paths) return routes

  // Try to extract tags from spec components or path structure
  for (const [path, methods] of Object.entries(paths)) {
    for (const [method, details] of Object.entries(methods)) {
      const d = details as Record<string, unknown>
      const tags = d.tags as string[] | undefined
      const inferredTag = path
        .split('/')
        .filter(Boolean)
        .find((s): s is string => !!s && !s.startsWith(':'))
      const tag = (tags && tags.length > 0 ? tags[0] : inferredTag) || 'default'
      routes.push({
        method: method.toUpperCase(),
        path,
        tag,
        params: extractPathParams(path),
      })
    }
  }

  return routes
}

function inferReturnType(method: string, path: string, typeName: string): string {
  if (method === 'DELETE') return 'void'
  if (method === 'GET') return path.includes(':') ? typeName : `${typeName}[]`
  return typeName
}

function generateMethodName(method: string, path: string, tag: string): string {
  const segments = path.split('/').filter((s) => s && !s.startsWith(':'))
  const last = segments[segments.length - 1] || tag
  const singular = singularize(last)

  switch (method) {
    case 'GET':
      return path.includes(':') ? `get${capitalize(singular)}` : `list${capitalize(last)}`
    case 'POST':
      return `create${capitalize(singular)}`
    case 'PUT':
    case 'PATCH':
      return `update${capitalize(singular)}`
    case 'DELETE':
      return `delete${capitalize(singular)}`
    default:
      return `${method.toLowerCase()}${capitalize(singular)}`
  }
}

function generateSdkCode(routes: ParsedRoute[], clientName: string): string {
  const lines: string[] = []

  lines.push('// Auto-generated SDK — do not edit')
  lines.push('// Generated by SpeexJS CLI')
  lines.push('')

  const typeNames = [
    ...new Set(
      routes
        .filter((r) => r.method !== 'DELETE')
        .map((r) => {
          const segments = r.path.split('/').filter((s) => s && !s.startsWith(':'))
          return capitalize(singularize(segments[segments.length - 1] || r.tag))
        }),
    ),
  ].sort()

  for (const name of typeNames) {
    lines.push(`export interface ${name} {`)
    lines.push('  [key: string]: unknown')
    lines.push('}')
    lines.push('')
  }

  const groups = new Map<string, ParsedRoute[]>()
  for (const route of routes) {
    const g = groups.get(route.tag) ?? []
    g.push(route)
    groups.set(route.tag, g)
  }

  const className = `${capitalize(clientName)}Client`
  lines.push(`export class ${className} {`)
  lines.push('  constructor(private baseUrl: string, private token?: string) {}')
  lines.push('')
  lines.push('  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {')
  lines.push("    const headers: Record<string, string> = { 'Content-Type': 'application/json' }")
  lines.push("    if (this.token) headers['Authorization'] = `Bearer ${this.token}`")
  lines.push('    const res = await fetch(`${this.baseUrl}${path}`, { method, headers, body: body ? JSON.stringify(body) : undefined })')
  lines.push('    if (!res.ok) {')
  lines.push('      const text = await res.text().catch(() => res.statusText)')
  lines.push('      throw new Error(`${res.status} ${text}`)')
  lines.push('    }')
  lines.push('    return res.status === 204 ? (undefined as T) : (res.json() as Promise<T>)')
  lines.push('  }')
  lines.push('')

  for (const [tag, tagRoutes] of groups) {
    lines.push(`  // ${capitalize(tag)}`)

    const usedNames = new Set<string>()

    for (const route of tagRoutes) {
      const segments = route.path.split('/').filter((s) => s && !s.startsWith(':'))
      const typeName = capitalize(singularize(segments[segments.length - 1] || tag))
      const returnType = inferReturnType(route.method, route.path, typeName)
      const hasBody = ['POST', 'PUT', 'PATCH'].includes(route.method)

      let methodName = generateMethodName(route.method, route.path, tag)
      if (usedNames.has(methodName)) {
        let suffix = 2
        while (usedNames.has(`${methodName}${suffix}`)) suffix++
        methodName = `${methodName}${suffix}`
      }
      usedNames.add(methodName)

      const paramParts: string[] = []
      for (const p of route.params) {
        paramParts.push(`${p.name}: ${p.type}`)
      }

      if (hasBody) paramParts.push(`data: Partial<${typeName}>`)

      const pathTemplate = route.path.replace(/:(\w+)/g, '${$1}')

      if (paramParts.length > 0) {
        lines.push(`  ${methodName}(${paramParts.join(', ')}): Promise<${returnType}> {`)
        lines.push(`    return this.request<${returnType}>('${route.method}', \`${pathTemplate}\`${hasBody ? ', data' : ''})`)
        lines.push('  }')
      } else {
        lines.push(`  ${methodName}(): Promise<${returnType}> {`)
        lines.push(`    return this.request<${returnType}>('${route.method}', '${route.path}')`)
        lines.push('  }')
      }
    }
  }

  lines.push('}')
  lines.push('')

  const factoryName = `create${capitalize(clientName)}Client`
  lines.push(`export const ${factoryName} = (baseUrl: string, token?: string): ${className} => new ${className}(baseUrl, token)`)
  lines.push('')

  return lines.join('\n')
}

export async function generateSdk(options: SdkGenOptions = {}): Promise<void> {
  const output = options.output || './sdk.ts'
  const clientName = options.name || 'api'
  const format = options.format || 'typescript'

  if (format !== 'typescript') {
    console.error(colors.red(`Unsupported format: ${format}`))
    process.exit(1)
  }

  const outPath = resolve(process.cwd(), output)
  const outDir = dirname(outPath)

  let routes: ParsedRoute[] = []

  const specPaths = [resolve(process.cwd(), 'openapi.json'), resolve(process.cwd(), 'dist/openapi.json')]

  for (const sp of specPaths) {
    if (existsSync(sp)) {
      try {
        const spec = JSON.parse(readFileSync(sp, 'utf-8'))
        routes = parseSpecIntoRoutes(spec)
        if (routes.length > 0) break
      } catch {
        continue
      }
    }
  }

  if (routes.length === 0) {
    routes = scanControllers()
  }

  if (routes.length === 0) {
    console.error(colors.red('No routes found. Create controllers in src/server/controllers/ or provide an openapi.json'))
    process.exit(1)
  }

  const sdkContent = generateSdkCode(routes, clientName)

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  writeFileSync(outPath, sdkContent, 'utf-8')
  console.log(`  ${colors.green('✓')} SDK generated (${routes.length} endpoints) → ${output}`)
}
