import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { colors } from '../../native/colors.js'

interface BuildFunctionOptions {
  target: 'lambda' | 'vercel' | 'cloudflare'
  outDir?: string
}

// ─── Helpers ──────────────────────────────────────────────────────────────

function findAppModule(cwd: string): string | null {
  const candidates = [
    resolve(cwd, 'dist/index.js'),
    resolve(cwd, 'dist/app.js'),
    resolve(cwd, 'dist/server/index.js'),
    resolve(cwd, 'dist/src/index.js'),
    resolve(cwd, 'dist/src/app.js'),
  ]

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      try {
        const content = readFileSync(candidate, 'utf-8')
        // Look for an export that looks like a SuperApp instance
        if (
          content.includes('SuperApp') ||
          content.includes('speexjs(') ||
          content.includes('speexjs (') ||
          content.includes('new SuperApp')
        ) {
          return candidate
        }
      } catch {
        continue
      }
    }
  }

  // Fallback: just return the first candidate that exists
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate
    }
  }

  return null
}

function detectAppExportName(modulePath: string): string | null {
  try {
    const content = readFileSync(modulePath, 'utf-8')
    // Look for default export
    if (content.includes('export default') || content.includes('exports.default')) {
      return 'default'
    }
    // Look for named 'app' export
    if (
      content.includes('export { app') ||
      content.includes('export const app') ||
      content.includes('exports.app') ||
      content.includes('export { app ')
    ) {
      return 'app'
    }
  } catch {
    /* ignore */
  }
  return 'default'
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`
}

// ─── Handler generators ───────────────────────────────────────────────────

function generateLambdaHandler(appModule: string, appExport: string): string {
  const relPath =
    './' +
    resolve(appModule)
      .replace(/\\/g, '/')
      .replace(/^.*?\/dist\//, '')

  return `// Auto-generated by speexjs build:function --target lambda
// AWS Lambda handler (API Gateway v2)
import { createLambdaHandler } from 'speexjs/server/edge/cloud-functions'

async function loadApp() {
  const mod = await import('${relPath}')
  return mod.${appExport} ?? mod.default
}

const cachedHandler = loadApp().then((app) => createLambdaHandler(app))

export async function handler(event: any, context: any): Promise<any> {
  const h = await cachedHandler
  return h(event, context)
}
`
}

function generateVercelHandler(appModule: string, appExport: string): string {
  const relPath =
    './' +
    resolve(appModule)
      .replace(/\\/g, '/')
      .replace(/^.*?\/dist\//, '')

  return `// Auto-generated by speexjs build:function --target vercel
// Vercel Serverless handler
import { createVercelHandler } from 'speexjs/server/edge/cloud-functions'

async function loadApp() {
  const mod = await import('${relPath}')
  return mod.${appExport} ?? mod.default
}

let cachedHandler: any = null

export default async function handler(req: any, res: any): Promise<void> {
  if (cachedHandler === null) {
    const app = await loadApp()
    cachedHandler = createVercelHandler(app)
  }
  return cachedHandler(req, res)
}
`
}

function generateCloudflareHandler(appModule: string, appExport: string): string {
  const relPath =
    './' +
    resolve(appModule)
      .replace(/\\/g, '/')
      .replace(/^.*?\/dist\//, '')

  return `// Auto-generated by speexjs build:function --target cloudflare
// Cloudflare Worker handler
import { createFetchHandler } from 'speexjs/server/edge/cloud-functions'

async function loadApp() {
  const mod = await import('${relPath}')
  return mod.${appExport} ?? mod.default
}

let cachedHandler: ((request: Request, env?: Record<string, unknown>, ctx?: unknown) => Promise<Response>) | null = null

export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: unknown): Promise<Response> {
    if (cachedHandler === null) {
      const app = await loadApp()
      cachedHandler = createFetchHandler(app)
    }
    return cachedHandler(request, env, ctx)
  },
}
`
}

function generateLambdaPackageJson(): string {
  return JSON.stringify(
    {
      name: 'speexjs-lambda-function',
      version: '1.0.0',
      type: 'module',
      dependencies: {
        speexjs: '^1.0.0',
      },
    },
    null,
    2,
  )
}

function generateCloudflareWrangler(handlerPath: string): string {
  return `name = "speexjs-cloudflare-worker"
main = "${handlerPath}"
compatibility_date = "2025-01-01"

[observability]
enabled = true
`
}

// ─── Main build command ───────────────────────────────────────────────────

export async function buildFunction(options?: Partial<BuildFunctionOptions>): Promise<void> {
  const opts: BuildFunctionOptions = {
    target: options?.target ?? 'lambda',
    outDir: options?.outDir ?? 'dist/functions',
  }

  const cwd = process.cwd()
  const target = opts.target

  console.log(`  ${colors.cyan('→')} Building cloud function for ${colors.bold(target)}...`)
  console.log()

  // Step 1: Compile with tsc
  if (existsSync(resolve(cwd, 'tsconfig.json'))) {
    console.log(`  ${colors.cyan('→')} Compiling TypeScript...`)
    try {
      execSync('tsc', { stdio: 'inherit', cwd })
      console.log(`  ${colors.green('✓')} TypeScript compilation complete`)
      console.log()
    } catch {
      console.error(`  ${colors.red('✗')} TypeScript compilation failed`)
      process.exit(1)
    }
  }

  // Step 2: Find the compiled app module
  const appModule = findAppModule(cwd)
  if (appModule === null) {
    console.error(`  ${colors.red('✗')} Could not find compiled app module in dist/`)
    console.log(`    Expected one of: dist/index.js, dist/app.js, dist/server/index.js`)
    console.log(`    Make sure your app exports a SuperApp instance.`)
    process.exit(1)
  }

  const appExport = detectAppExportName(appModule) ?? 'app'
  const relModule = resolve(appModule).replace(/\\/g, '/')
  console.log(`  ${colors.dim('•')} Found app module: ${relModule}`)
  console.log(`  ${colors.dim('•')} Using export: ${colors.cyan(appExport)}`)
  console.log()

  // Step 3: Generate handler for target platform
  const outDir = resolve(cwd, opts.outDir!, target)
  mkdirSync(outDir, { recursive: true })

  let handlerContent = ''
  let handlerFilename = ''

  switch (target) {
    case 'lambda': {
      handlerContent = generateLambdaHandler(appModule, appExport)
      handlerFilename = 'handler.mjs'
      break
    }
    case 'vercel': {
      handlerContent = generateVercelHandler(appModule, appExport)
      handlerFilename = 'handler.mjs'
      break
    }
    case 'cloudflare': {
      handlerContent = generateCloudflareHandler(appModule, appExport)
      handlerFilename = 'handler.mjs'
      break
    }
  }

  const handlerPath = resolve(outDir, handlerFilename)
  writeFileSync(handlerPath, handlerContent, 'utf-8')
  const fileSize = Buffer.byteLength(handlerContent, 'utf-8')

  // Step 4: Generate platform-specific extras
  switch (target) {
    case 'lambda': {
      // Generate a package.json for the Lambda deployment bundle
      const pkgPath = resolve(outDir, 'package.json')
      if (!existsSync(pkgPath)) {
        writeFileSync(pkgPath, generateLambdaPackageJson(), 'utf-8')
        console.log(`  ${colors.green('✓')} Generated package.json for Lambda bundle`)
      }
      console.log()
      console.log(`  ${colors.bold('Lambda deployment:')}`)
      console.log(`  ${colors.dim('  cd')} ${resolve(opts.outDir!, target).replace(/\\/g, '/')}`)
      console.log(`  ${colors.dim('  npm install')}`)
      console.log(`  ${colors.dim('  zip -r function.zip .')}`)
      console.log(`  ${colors.dim('  aws lambda create-function --function-name my-speexjs-app \\')}`)
      console.log(`  ${colors.dim('      --runtime nodejs20.x --handler handler.handler \\')}`)
      console.log(`  ${colors.dim('      --zip-file fileb://function.zip --role arn:aws:iam::...')}`)
      break
    }
    case 'vercel': {
      // For Vercel, also write to api/ directory for direct use
      const vercelApiDir = resolve(cwd, 'api')
      mkdirSync(vercelApiDir, { recursive: true })
      const vercelHandlerPath = resolve(vercelApiDir, 'index.mjs')
      writeFileSync(vercelHandlerPath, handlerContent, 'utf-8')
      console.log(`  ${colors.green('✓')} Also written to api/index.mjs for Vercel`)
      console.log()
      console.log(`  ${colors.bold('Vercel deployment:')}`)
      console.log(`  ${colors.dim('  vercel --prod')}`)
      console.log(`  ${colors.dim('  (Make sure vercel.json or project.json is configured)')}`)
      break
    }
    case 'cloudflare': {
      // Generate wrangler.toml in the output directory
      const wranglerPath = resolve(outDir, 'wrangler.toml')
      if (!existsSync(wranglerPath)) {
        writeFileSync(wranglerPath, generateCloudflareWrangler(handlerFilename), 'utf-8')
        console.log(`  ${colors.green('✓')} Generated wrangler.toml`)
      }
      console.log()
      console.log(`  ${colors.bold('Cloudflare Workers deployment:')}`)
      console.log(`  ${colors.dim('  cd')} ${resolve(opts.outDir!, target).replace(/\\/g, '/')}`)
      console.log(`  ${colors.dim('  npx wrangler deploy')}`)
      break
    }
  }

  console.log()
  console.log(`  ${colors.green('✓')} Handler written to ${handlerPath} (${formatBytes(fileSize)})`)
  console.log()
  console.log(`  ${colors.dim('Tip:')} Run ${colors.cyan('speexjs deploy --' + target)} for full deployment configuration.`)
}
