import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { colors } from '../../native/colors.js'

interface DeployOptions {
  docker?: boolean
  vercel?: boolean
  railway?: boolean
  render?: boolean
  flyio?: boolean
  blueGreen?: boolean
  rollback?: boolean
  init?: boolean
  domain?: string
  activePort?: number
  standbyPort?: number
}

const TARGETS = ['docker', 'vercel', 'railway', 'render', 'flyio', 'blue-green'] as const

function generateDockerfile(): string {
  return [
    '# Build stage',
    'FROM node:20-alpine AS build',
    'WORKDIR /app',
    'COPY package*.json ./',
    'RUN npm ci',
    'COPY . .',
    'RUN npm run build',
    '',
    '# Production stage',
    'FROM node:20-alpine',
    'WORKDIR /app',
    'COPY --from=build /app/dist ./dist',
    'COPY --from=build /app/package*.json ./',
    'RUN npm ci --production',
    'EXPOSE 3000',
    'CMD ["node", "dist/index.js"]',
  ].join('\n')
}

function generateDockerCompose(): string {
  return `services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
`
}

function generateVercelJson(): string {
  return JSON.stringify({
    version: 2,
    buildCommand: 'npm run build',
    outputDirectory: 'dist',
    installCommand: 'npm ci',
    devCommand: 'npm run dev',
  }, null, 2)
}

function generateRailwayJson(): string {
  return JSON.stringify({
    $schema: 'https://railway.app/railway.schema.json',
    build: { builder: 'NIXPACKS', buildCommand: 'npm run build' },
    deploy: { startCommand: 'node dist/index.js', healthcheckPath: '/', restartPolicyType: 'ON_FAILURE', numReplicas: 1 },
  }, null, 2)
}

function generateRenderYaml(): string {
  return `services:
  - type: web
    name: my-speexjs-app
    env: node
    buildCommand: npm run build
    startCommand: node dist/index.js
    healthCheckPath: /
    autoDeploy: true
`
}

function generateFlyToml(): string {
  return `app = "my-speexjs-app"
primary_region = "iad"

[build]
  command = "npm run build"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
`
}

// ─── Blue-Green Zero-Downtime Deployment ─────────────────────────

interface BlueGreenConfig {
  activePort: number
  standbyPort: number
  healthCheckPath: string
  healthCheckInterval: number
  healthCheckTimeout: number
  unhealthyThreshold: number
  nginxConfigPath: string
}

const DEFAULT_BLUE_GREEN: BlueGreenConfig = {
  activePort: 3000,
  standbyPort: 3001,
  healthCheckPath: '/health',
  healthCheckInterval: 2000,
  healthCheckTimeout: 5000,
  unhealthyThreshold: 3,
  nginxConfigPath: '/etc/nginx/sites-enabled/speexjs',
}

function generateBlueGreenNginxConfig(domain: string, activePort: number, standbyPort: number): string {
  return `# Auto-generated by SpeexJS Blue-Green Deploy
# ${new Date().toISOString()}

upstream speexjs_active {
    server 127.0.0.1:${activePort};
}

upstream speexjs_standby {
    server 127.0.0.1:${standbyPort};
}

server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://speexjs_active;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location /health {
        proxy_pass http://speexjs_active;
        access_log off;
        return 200 "healthy\\n";
    }
}
`
}

function generateSwapScript(): string {
  return String.raw`#!/bin/bash
# Auto-generated by SpeexJS Blue-Green Deploy
set -e

ACTIVE_PORT=$1
STANDBY_PORT=$2
NGINX_CONFIG=$3

echo "🔄 Blue-Green: Switching traffic from :$ACTIVE_PORT to :$STANDBY_PORT..."

sed -i "s/:$ACTIVE_PORT/:$STANDBY_PORT/g" "$NGINX_CONFIG"
nginx -t || { echo "❌ Nginx config test failed"; exit 1; }
nginx -s reload

echo "✅ Traffic switched to :$STANDBY_PORT"
echo "ℹ️  Old instance on :$ACTIVE_PORT will be stopped after drain"
`
}

function generateHealthCheckScript(): string {
  const D = '$'
  return String.raw`#!/bin/bash
# Auto-generated by SpeexJS Health Check

URL=${D}1
TIMEOUT=${D}{2:-5}
INTERVAL=${D}{3:-2}
THRESHOLD=${D}{4:-3}

echo "🔍 Health checking $URL..."

for i in $(seq 1 $THRESHOLD); do
  STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time $TIMEOUT $URL 2>/dev/null || echo "000")
  if [ "$STATUS" = "200" ]; then
    echo "   ✅ Attempt $i: Health check passed ($STATUS)"
    exit 0
  fi
  echo "   ⚠️  Attempt $i: Health check returned $STATUS, retrying in ${D}{INTERVAL}s..."
  sleep $INTERVAL
done

echo "❌ Health check failed after $THRESHOLD attempts"
exit 1
`
}

function printDeployInstructions(target: string): void {
  console.log()
  console.log(`  ${colors.bold(`Deploy instructions for ${target}:`)}`)
  console.log()

  if (target === 'docker') {
    console.log(`  ${colors.cyan('1.')} Build and start containers:`)
    console.log(`     ${colors.dim('docker compose up -d --build')}`)
    console.log(`  ${colors.cyan('2.')} Check container status:`)
    console.log(`     ${colors.dim('docker compose ps')}`)
    console.log(`  ${colors.cyan('3.')} View logs:`)
    console.log(`     ${colors.dim('docker compose logs -f app')}`)
    console.log(`  ${colors.cyan('4.')} Stop containers:`)
    console.log(`     ${colors.dim('docker compose down')}`)
  } else if (target === 'vercel') {
    console.log(`  ${colors.cyan('1.')} Install Vercel CLI:`)
    console.log(`     ${colors.dim('npm i -g vercel')}`)
    console.log(`  ${colors.cyan('2.')} Deploy:`)
    console.log(`     ${colors.dim('vercel --prod')}`)
    console.log(`  ${colors.bold('Environment variables:')}`)
    console.log(`  ${colors.dim('Set NODE_ENV, DATABASE_URL, APP_KEY in Vercel dashboard')}`)
  } else if (target === 'railway') {
    console.log(`  ${colors.cyan('1.')} Install Railway CLI:`)
    console.log(`     ${colors.dim('npm i -g @railway/cli')}`)
    console.log(`  ${colors.cyan('2.')} Login and deploy:`)
    console.log(`     ${colors.dim('railway login && railway up')}`)
  } else if (target === 'render') {
    console.log(`  ${colors.cyan('1.')} Push code to Git repository`)
    console.log(`  ${colors.cyan('2.')} Go to dashboard.render.com and connect repo`)
    console.log(`  ${colors.cyan('3.')} Render auto-detects the config from render.yaml`)
  } else if (target === 'flyio') {
    console.log(`  ${colors.cyan('1.')} Install flyctl:`)
    console.log(`     ${colors.dim('powershell "iwr https://fly.io/install.ps1 | iex"')}`)
    console.log(`  ${colors.cyan('2.')} Launch:`)
    console.log(`     ${colors.dim('fly launch --generate-name')}`)
    console.log(`  ${colors.cyan('3.')} Deploy:`)
    console.log(`     ${colors.dim('fly deploy')}`)
  }

  console.log()
}

// ─── Blue-Green Deploy ──────────────────────────────────────────

async function deployBlueGreen(options: DeployOptions): Promise<void> {
  const baseDir = resolve(process.cwd())
  const activePort = options.activePort ?? DEFAULT_BLUE_GREEN.activePort
  const standbyPort = options.standbyPort ?? DEFAULT_BLUE_GREEN.standbyPort
  const domain = options.domain ?? 'localhost'

  console.log(`\n  ${colors.bold('🌊 Blue-Green Deployment')}`)
  console.log(`  ${colors.dim('─'.repeat(50))}`)
  console.log(`  Active port:  ${colors.cyan(String(activePort))}`)
  console.log(`  Standby port: ${colors.cyan(String(standbyPort))}`)
  console.log(`  Domain:       ${colors.cyan(domain)}`)
  console.log()

  // Generate nginx config
  console.log(`  ${colors.cyan('→')} Generating nginx configuration...`)
  const nginxConfig = generateBlueGreenNginxConfig(domain, activePort, standbyPort)
  const deployDir = resolve(baseDir, 'deploy')
  if (!existsSync(deployDir)) {
    writeFileSync(resolve(deployDir, '.gitkeep'), '', 'utf-8')
  }
  writeFileSync(resolve(deployDir, 'nginx-blue-green.conf'), nginxConfig, 'utf-8')
  console.log(`  ${colors.green('✅')} deploy/nginx-blue-green.conf`)

  // Generate swap script
  const swapScript = generateSwapScript()
  writeFileSync(resolve(deployDir, 'swap.sh'), swapScript, 'utf-8')
  console.log(`  ${colors.green('✅')} deploy/swap.sh`)

  // Generate health check script
  const healthScript = generateHealthCheckScript()
  writeFileSync(resolve(deployDir, 'health-check.sh'), healthScript, 'utf-8')
  console.log(`  ${colors.green('✅')} deploy/health-check.sh`)

  console.log()
  console.log(`  ${colors.bold('📋 Deployment Steps:')}`)
  console.log(`  ${colors.cyan('1.')} Build: npm run build`)
  console.log(`  ${colors.cyan('2.')} Start standby: PORT=${standbyPort} node dist/index.js &`)
  console.log(`  ${colors.cyan('3.')} Health check: bash deploy/health-check.sh http://localhost:${standbyPort}/health`)
  console.log(`  ${colors.cyan('4.')} Swap: bash deploy/swap.sh ${activePort} ${standbyPort} ${nginxConfig}`)
  console.log(`  ${colors.cyan('5.')} Rollback: speexjs deploy --rollback`)
  console.log()
  console.log(`  ${colors.green('✓')} Blue-green configuration complete`)
}

async function rollbackDeploy(options: DeployOptions): Promise<void> {
  const activePort = options.activePort ?? DEFAULT_BLUE_GREEN.activePort
  const standbyPort = options.standbyPort ?? DEFAULT_BLUE_GREEN.standbyPort

  console.log(`\n  ${colors.bold('↩️  Rolling Back Deployment')}`)
  console.log(`  ${colors.dim('─'.repeat(50))}`)
  console.log(`  ${colors.cyan('→')} Switching traffic back to :${activePort}...`)
  console.log()
  console.log(`  ${colors.dim(`  Run: sed -i 's/:${standbyPort}/:${activePort}/g' deploy/nginx-blue-green.conf`)}`)
  console.log(`  ${colors.dim('  Run: nginx -t && nginx -s reload')}`)
  console.log()
  console.log(`  ${colors.green('✓')} Rollback initiated`)
}

// ─── Main Deploy Function ───────────────────────────────────────

export async function deploy(options?: Partial<DeployOptions>): Promise<void> {
  const opts: DeployOptions = {
    docker: options?.docker ?? false,
    vercel: options?.vercel ?? false,
    railway: options?.railway ?? false,
    render: options?.render ?? false,
    flyio: options?.flyio ?? false,
    blueGreen: options?.blueGreen ?? false,
    rollback: options?.rollback ?? false,
    init: options?.init ?? false,
    domain: options?.domain,
    activePort: options?.activePort,
    standbyPort: options?.standbyPort,
  }

  // Handle rollback early
  if (opts.rollback) {
    await rollbackDeploy(opts)
    return
  }

  // Handle blue-green
  if (opts.blueGreen) {
    await deployBlueGreen(opts)
    return
  }

  // Find target
  let target = ''
  for (const t of TARGETS) {
    if (t === 'blue-green') continue // handled above
    if (opts[t]) {
      target = t
      break
    }
  }

  if (!target) {
    console.log(`  ${colors.cyan('?')} Select deployment target:`)
    TARGETS.filter(t => t !== 'blue-green').forEach((t, i) => {
      console.log(`  ${colors.dim(`${i + 1})`)} ${t.charAt(0).toUpperCase() + t.slice(1)}`)
    })
    console.log()
    process.stdout.write(`  ${colors.cyan('→')} Enter number (1-${TARGETS.length - 1}): `)

    target = await new Promise<string>((resolve) => {
      process.stdin.once('data', (data) => {
        const input = data.toString().trim()
        const idx = Number.parseInt(input, 10) - 1
        const filtered = TARGETS.filter(t => t !== 'blue-green')
        if (idx >= 0 && idx < filtered.length) {
          resolve(filtered[idx]!)
        } else {
          console.log(`  ${colors.red('Invalid choice, defaulting to Docker')}`)
          resolve('docker')
        }
      })
    })
  }

  const baseDir = resolve(process.cwd())

  if (target === 'docker') {
    const dockerfilePath = resolve(baseDir, 'Dockerfile')
    if (!existsSync(dockerfilePath) || opts.init) {
      writeFileSync(dockerfilePath, generateDockerfile(), 'utf-8')
      console.log(`  ${colors.green('✅')} Dockerfile created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} Dockerfile already exists`)
    }

    const composePath = resolve(baseDir, 'docker-compose.yml')
    if (!existsSync(composePath) || opts.init) {
      writeFileSync(composePath, generateDockerCompose(), 'utf-8')
      console.log(`  ${colors.green('✅')} docker-compose.yml created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} docker-compose.yml already exists`)
    }

    if (!opts.init) printDeployInstructions('docker')
    console.log(`  ${colors.green('✓')} Docker setup complete`)
  }

  if (target === 'vercel') {
    const vercelJsonPath = resolve(baseDir, 'vercel.json')
    if (!existsSync(vercelJsonPath) || opts.init) {
      writeFileSync(vercelJsonPath, generateVercelJson(), 'utf-8')
      console.log(`  ${colors.green('✅')} vercel.json created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} vercel.json already exists`)
    }
    if (!opts.init) printDeployInstructions('vercel')
    console.log(`  ${colors.green('✓')} Vercel setup complete`)
  }

  if (target === 'railway') {
    const railwayPath = resolve(baseDir, 'railway.json')
    if (!existsSync(railwayPath) || opts.init) {
      writeFileSync(railwayPath, generateRailwayJson(), 'utf-8')
      console.log(`  ${colors.green('✅')} railway.json created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} railway.json already exists`)
    }
    if (!opts.init) printDeployInstructions('railway')
    console.log(`  ${colors.green('✓')} Railway setup complete`)
  }

  if (target === 'render') {
    const renderPath = resolve(baseDir, 'render.yaml')
    if (!existsSync(renderPath) || opts.init) {
      writeFileSync(renderPath, generateRenderYaml(), 'utf-8')
      console.log(`  ${colors.green('✅')} render.yaml created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} render.yaml already exists`)
    }
    if (!opts.init) printDeployInstructions('render')
    console.log(`  ${colors.green('✓')} Render setup complete`)
  }

  if (target === 'flyio') {
    const flyPath = resolve(baseDir, 'fly.toml')
    if (!existsSync(flyPath) || opts.init) {
      writeFileSync(flyPath, generateFlyToml(), 'utf-8')
      console.log(`  ${colors.green('✅')} fly.toml created`)
    } else {
      console.log(`  ${colors.yellow('⚠')} fly.toml already exists`)
    }
    if (!opts.init) printDeployInstructions('flyio')
    console.log(`  ${colors.green('✓')} Fly.io setup complete`)
  }
}

export async function deployWithBlueGreen(options: DeployOptions): Promise<void> {
  await deployBlueGreen(options)
}
